### ISSUE TITLE
can poiseuille.cuds be generated?

### ISSUE THREAD

**Issue by nathanfranklin** [simphony/simphony-numerrin#3]
Would it be possible to delete the `poiseuille.cuds` file from the repository and only generate it (or better yet, just generate the Mesh that it contains) when the tests are run?  This is similar to the issue in simphony/simphony-openfoam#26

**Comment by khiltunen** [comment]
This is similar to #26 and can be done if the corresponding foam mesh files are added to package.

**Comment by khiltunen** [comment]
Do  you think that it would be better to make these changes to tests and examples using cuds files along wth the PR #23, while it will be merged to same master hopefully in short time ?

**Comment by nathanfranklin** [comment]
> This is similar to #26 and can be done if the corresponding foam mesh files are added to package.

is openfoam required here to generate this example mesh?   

> Do you think that it would be better to make these changes to tests and examples using cuds files along wth the PR #23, while it will be merged to same master hopefully in short time ?

the PR simphony/simphony-openfoam#23 is for openfoam.

for the time-being, it would be best that a fixed version of simphony-common (0.1.3) is set in the requirements files and in the setup.py and in the README.  then the tests will run (using the `simplemesh.cuds`) and the example will run (using `poiseuille.cuds`).  Currently, both the needed files can't be read by the latest version of simphony-common.

**Comment by khiltunen** [comment]
Here the same cuds -file is used as in openfoam tests. Maybe it is better now to stick on version 0.1.3. What is the right syntax for required_packages in setup.py to get 0.1.3 in use ?

**Comment by itziakos** [comment]
@nathanfranklin  and @khiltunen PR #4 sets the simphony commons to 0.1.3 in the requirements.txt. Please note that we should also update the documentation.

**Comment by nathanfranklin** [comment]
Closed by #9
